top_dir: /home/zhangh5/work/Tapestri_batch2/analysis/cn_clones
cohort_name: RA16_29

####################
# not applicable for panel level
nrestarts: 10
seeds: 0
maxcn: 10
####################

cn_calling_mode: cohort # cohort or single-sample
panel_nseeds: 100
panel_maxcn: 20
panel_amplicon_parameters: /home/zhangh5/work/Tapestri_batch2/analysis/cn_clones/train-normal_samples/train-combined_8_normals/NB_train-combined_8_normals-results.gene_added.csv
# panel_amplicon_parameters: /home/zhangh5/work/Tapestri_batch2/analysis/cn_clones/reference/panel2_nb_results-TP53_fixed.csv

# Number of clones to try. These will be executed in parallel.
nclones:
    - 2
    - 3
    - 4
    - 5
    # - 6
    # - 7
    # - 8
    # - 9
    # - 10

samples:
    - RA16_29-2_1
    - RA16_29-16_1
    - RA16_29-24_1
    - RA16_29-25_1
    - RA16_29-32_1
    # - RA16_29-40_2
    - RA16_29-47_1

# Irrelevant for tumor sample cn-calling
genes:
    - ARID1A
    - BRCA2
    - BMPR1A
    - ACVR2A
    - BMPR1B
    - TGFBR2
    - SMAD4
    - BMPR2
    - RNF43
    - ATM
    - SMAD2
    - KMT2C
    - ACVR1B
    - ARID1B
    - SMAD3
    - TGFBR1
    - KMT2D
    - KAT5
    - MYC
    - BAP1
    - TP53
    - GATA6
    - ARID2
    - BRCA1
    - CREBBP
    - KRAS
    - CDKN2A
    - MTOR
    - FGFR1
    - ARHGAP35

tsv_file_dict:
    RA16_29-2_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-2_1/OUTPUTS_from_m2_f/RA16_29-2_1.per_amplicon_read_counts.tsv
    RA16_29-16_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-16_1/OUTPUTS_from_m2_f/RA16_29-16_1.per_amplicon_read_counts.tsv
    RA16_29-24_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-24_1/OUTPUTS_from_m2_f/RA16_29-24_1.per_amplicon_read_counts.tsv
    RA16_29-25_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-25_1/OUTPUTS_from_m2_f/RA16_29-25_1.per_amplicon_read_counts.tsv
    RA16_29-32_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-32_1/OUTPUTS_from_m2_f/RA16_29-32_1.per_amplicon_read_counts.tsv
    # RA16_29-40_2: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-40_2/OUTPUTS_from_m2_f/RA16_29-40_2.per_amplicon_read_counts.tsv
    RA16_29-47_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-47_1/OUTPUTS_from_m2_f/RA16_29-47_1.per_amplicon_read_counts.tsv

input_H5:
    RA16_29-2_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-2_1/OUTPUTS_from_m2_f/RA16_29-2_1_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5
    RA16_29-16_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-16_1/OUTPUTS_from_m2_f/RA16_29-16_1_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5
    RA16_29-24_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-24_1/OUTPUTS_from_m2_f/RA16_29-24_1_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5
    RA16_29-25_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-25_1/OUTPUTS_from_m2_f/RA16_29-25_1_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5
    RA16_29-32_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-32_1/OUTPUTS_from_m2_f/RA16_29-32_1_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5
    # RA16_29-40_2: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-40_2/OUTPUTS_from_m2_f/RA16_29-40_2_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5
    RA16_29-47_1: /home/zhangh5/work/Tapestri_batch2/pipeline_results_custom/RA16_29/RA16_29-47_1/OUTPUTS_from_m2_f/RA16_29-47_1_DNA_CNV_m2_f.bulk_annotated.ponv1_filtered.h5

# Deprecated???
# amplicon_parameters: /home/zhangh5/work/Tapestri_batch2/analysis/cn_clones/reference/panel2_nb_results-TP53_fixed.csv

scripts:
    cn_calling_panel_level: /home/zhangh5/work/Tapestri_project/cn-calling/mixed_NB_EM_panel_level_with_normal.py
    gather_NB_EM_results: /home/zhangh5/work/Tapestri_project/cn-calling/gather_NB_EM_results.py 
    add_ploidy_layers_to_h5: /home/zhangh5/work/Tapestri_project/cn-calling/add_ploidy_layers_to_h5.py